services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT}:5173"  # Use environment variable
    environment:
      VITE_MODE: ${VITE_MODE}
      VITE_DEFAULT_PAGE_SIZE: ${VITE_DEFAULT_PAGE_SIZE}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    volumes:
      - .:/app  # Add volume for hot reload
      - /app/node_modules
    networks:
      - barnabas-network
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: 
      context: ${API_CONTEXT_PATH}
    environment:
      PORT: ${API_PORT}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - barnabas-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_dev:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - barnabas-network

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=$MINIO_ACCESS_KEY
      - MINIO_ROOT_PASSWORD=$MINIO_SECRET_KEY
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - barnabas-network
      
volumes:
  mysql_data_dev:

networks:
  barnabas-network:
    driver: bridge