services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "${FRONTEND_PORT}:4173" 
    environment:
      VITE_MODE: ${VITE_MODE}
      VITE_DEFAULT_PAGE_SIZE: ${VITE_DEFAULT_PAGE_SIZE}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    networks:
      - barnabas-network
    depends_on:
      - api
    restart: unless-stopped

  api:
    build: 
      context: ${API_CONTEXT_PATH}
    environment:
      PORT: ${API_PORT}
      MYSQL_HOST: db
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      - barnabas-network
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data_prod:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - barnabas-network

volumes:
  mysql_data_prod:

networks:
  barnabas-network:
    driver: bridge