import {
    EducationLevel,
    Gender,
    MaritalStatus,
    MarriageType,
    MemberRole,
} from "@/constants";
import { MemberCreateFormValues } from "../interactors/member-create/schemas/schemas.member";

export const sampleMember: Partial<MemberCreateFormValues> = {
    "envelopeNumber": "1000",
    "firstName": "Okello",
    "middleName": "William",
    "lastName": "Gerald",
    "gender": Gender.Male,
    "dateOfBirth": new Date(1990),
    "placeOfBirth": "Geita",
    "profilePhoto": undefined,
    "phoneNumber": "+255623165374",
    "email": "hi@okellogerald.com",
    "maritalStatus": MaritalStatus.Single,
    "marriageType": MarriageType.None,
    "dateOfMarriage": undefined,
    "spouseName": undefined,
    "placeOfMarriage": undefined,
    "spousePhoneNumber": undefined,
    "residenceNumber": "Plot 25, House 1",
    "residenceBlock": "Goba",
    "postalBox": "P.O. Box 67171",
    "residenceArea": "Goba Kulangwa",
    "formerChurch": undefined,
    "occupation": "Software Developer",
    "placeOfWork": "Temboplus",
    "educationLevel": EducationLevel.Bachelors,
    "profession": "IT",
    "memberRole": MemberRole.Regular,
    "isBaptized": true,
    "isConfirmed": false,
    "partakesLordSupper": true,
    "fellowshipId": "",
    "nearestMemberName": undefined,
    "nearestMemberPhone": undefined,
    "attendsFellowship": true,
    "fellowshipAbsenceReason": undefined,
};
