import { EducationLevel, Gender, MaritalStatus, MemberRole } from "@/constants";
import { MemberFormValues } from "../interactors/member-create/schemas/schemas.member";

export const sampleMember: Partial<MemberFormValues> = {
    "envelopeNumber": "1234",
    "firstName": "Aisha",
    "middleName": "Fatma",
    "lastName": "Kassim",
    "gender": Gender.Male,
    "dateOfBirth": new Date(),
    "placeOfBirth": "Dar es Salaam",
    "profilePhoto":
        "https://img.freepik.com/free-vector/hand-drawn-ethnic-beauty-illustration_23-2150216615.jpg?ga=GA1.1.81028063.1741691766&semt=ais_authors_boost",
    "phoneNumber": "+255621987654",
    "email": "aisha.kassim@example.co.tz",
    "maritalStatus": MaritalStatus.Single,
    "marriageType": undefined,
    "dateOfMarriage": undefined,
    "spouseName": undefined,
    "placeOfMarriage": undefined,
    "spousePhoneNumber": undefined,
    "residenceNumber": "Plot 12, House 3",
    "residenceBlock": "Mikocheni",
    "postalBox": "P.O. Box 12345",
    "residenceArea": "Mikocheni B",
    "formerChurch": "Masjid Quba",
    "occupation": "Teacher",
    "placeOfWork": "Mlimani Primary School",
    "educationLevel": EducationLevel.Certificate,
    "profession": "Education",
    "memberRole": MemberRole.Regular,
    "isBaptized": false,
    "isConfirmed": false,
    "partakesLordSupper": false,
    "fellowshipId": "b8976543210fedcba987654321012345",
    "nearestMemberName": "Salim Juma",
    "nearestMemberPhone": "+255754321987",
    "attendsFellowship": true,
    "fellowshipAbsenceReason": undefined,
};
